cart/urls.py
from django.urls import path

from .views import *


app_name = 'cart'
urlpatterns = [
    path('', cart_detail, name='detail'),
    path('add/<slug:product_slug>', card_add, name='add'),
    path('remove/<slug:product_slug>', card_remove, name='remove')
]

main_app/urls.py
from django.urls import path

from .views import *


app_name = 'main_app'
urlpatterns = [
    path('', MainPage, name='main')
]

orders/urls.py
from django.urls import path
from .views import order_create

app_name = 'orders'
urlpatterns = [
    path('order_create/', order_create, name='order_create')
]

shop_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from shop_site import settings
from main_app.views import pageNotFound

urlpatterns = [
    path('admin/', admin.site.urls),
    path('orders/', include('orders.urls', namespace='orders')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('catalog/', include('catalog.urls', namespace='catalog')),
    path('users_system/', include('users_system.urls', namespace='users_system')),
    path('', include('main_app.urls', namespace='main_app'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = pageNotFound

cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    override = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponse
from django.views.decorators.http import require_POST

from .cart import Cart
from .forms import CartAddProductForm
from catalog.models import Product

# Create your views here.
@require_POST
def card_add(request, product_slug):
    cart = Cart(request)
    product = get_object_or_404(Product, slug=product_slug)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        form_data = form.cleaned_data
        cart.add(product=product,
                 quantity=form_data['quantity'],
                 override_quantity=form_data['override'])
    return redirect('cart:detail')

@require_POST
def card_remove(request, product_slug):
    cart = Cart(request)
    product = get_object_or_404(Product, slug=product_slug)
    cart.remove(product.id)
    return redirect('cart:detail')

def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={
            'quantity': item['quantity'],
            'override': True
        })
    return render(request, 'cart/cart_detail.html', {'title': 'Корзина', 'cart': cart})
    # return render('main_app/main.html', {'title': 'Из представления корзины.'})
    # return HttpResponse('Содержимое корзины.')

cart/templates/cart/cart_detail.html
{% extends 'main_app/base.html' %}

{% block main %}
<h3>{{ title }}</h3>
<table>
    <thead>
        <tr>
            <th>Image</th>
            <th>Product</th>
            <th>Quantity</th>
            <th>Remove</th>
            <th>Unit price</th>
            <th>Price</th>
        </tr>
    </thead>
    <tbody>
    {% for item in cart %}
    {% with product=item.product %}
        <tr>
            <td>
                <a href="#">
                    <img src="/media/{{ product.image }}">
                </a>
            </td>
            <td>{{ product.name }}</td>
            <td>
                <form method="POST" action="{% url 'cart:add' product.slug %}">
                    {% csrf_token %}
                    {{ item.update_quantity_form.quantity }}
                    {{ item.update_quantity_form.override }}
                    <button type="submit">Обновить</button>
                </form>
            </td>
            <td>
                <form method="POST" action="{% url 'cart:remove' product.slug %}">
                    {% csrf_token %}
                    <button type="submit">Удалить</button>
                </form>
            </td>
            <td>${{ item.price }}</td>
            <td>${{ item.total_price }}</td>
        </tr>
    {% endwith %}
    {% endfor %}
    </tbody>
    <tfoot>
        <tr>
            <td>Всего:</td>
            <td colspan="4"></td>
            <td>${{ cart.get_total_price }}</td>
        </tr>
    </tfoot>
</table>
<a href="{% url 'main_app:main' %}">На главную</a>
<a href="{% url 'orders:order_create' %}">Оформить заказ</a>
{% endblock %}