cart/urls.py
from django.urls import path

from .views import *


app_name = 'cart'
urlpatterns = [
    path('', cart_detail, name='detail'),
    path('add/<slug:product_slug>', card_add, name='add'),
    path('remove/<slug:product_slug>', card_remove, name='remove')
]

catalog/urls.py
from django.urls import path

from .views import *


app_name = 'catalog'
urlpatterns = [
    path('', MainCatalogPage.as_view(), name='main_catalog'),
    path('<slug:category_slug>/<slug:product_slug>/', ProductDetail.as_view(), name='product_detail'),
    path('product_list_by_category/<slug:category_slug>', ProductsByCategory.as_view(), name='product_list_by_category')
]

main_app/urls.py
from django.urls import path

from .views import *


app_name = 'main_app'
urlpatterns = [
    path('', MainPage, name='main')
]

shop_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from shop_site import settings
from main_app.views import pageNotFound

urlpatterns = [
    path('admin/', admin.site.urls),
    path('orders/', include('orders.urls', namespace='orders')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('catalog/', include('catalog.urls', namespace='catalog')),
    path('users_system/', include('users_system.urls', namespace='users_system')),
    path('', include('main_app.urls', namespace='main_app'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = pageNotFound

users_system/urls.py
from django.urls import path

from .views import RegisterUser, LoginUser, logout_user


app_name = 'users_system'
urlpatterns = [
    path('register/', RegisterUser.as_view(), name='register'),
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', logout_user, name="logout")
]

main_app/models.py
from django.db import models

# Create your models here.

main_app/views.py
from django.shortcuts import render

# Create your views here.
def MainPage(request):
    return render(request, 'main_app/main.html', {'title': 'Главная'})
    
def pageNotFound(request, exception):
    return render('main_app/404.html', {'title': 'Такой страницы нет.'})

main_app/templates/main_app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="{% static 'main_app/css/base.css' %}">
    {% block css_links %}{% endblock %}
    <script src="{% static 'main_app/js/base.js' %}"></script>
    {% block js_links %}{% endblock %}
</head>
<body>
    <section class="wrapper">
        <header class="wrapper__header header">
            <h1 class="header__site-name">Интернет-магазин</h1>
            <section>
                {% if request.user.is_authenticated %}
                    <span>{{ user.first_name }} {{ user.last_name }}</span> | <a href="{% url 'users_system:logout' %}">Выйти</a>
                {% else %}
                    <a href="{% url 'users_system:login' %}">Войти</a>
                    <a href="{% url 'users_system:register' %}">Регистрация</a>
                {% endif %}
            </section>
            <section class="header__cart">
                {% with count_items=cart|length %}
                    {% if count_items > 0 %}
                        <a href="{% url 'cart:detail' %}">
                            {{ count_items }} тов. | ${{ cart.get_total_price }}
                        </a>
                    {% else %}
                        Корзина пуста
                    {% endif %}
                {% endwith %}
            </section>
        </header>
        <main class="wrapper__main main">
            {% block main %}{% endblock %}
        </main>
        <footer class="wrapper__footer footer">
            <section class="footer__site-map">Карта сайта</section>
            <section class="footer__social-network">Соц. сети</section>
        </footer>
    </section>
</body>
</html>

main_app/templates/main_app/main.html
{% extends 'main_app/base.html' %}
{% load static %}

{% block css_links %}
<link rel="stylesheet" href="{% static 'main_app/css/main_page.css' %}">
{% endblock %}

{% block main %}
    <a href="{% url 'catalog:main_catalog' %}">Каталог</a>
    <h2>{{ title }}</h2>
    <section class="slyder">
        <h3 class="slyder__header">Слайдер</h3>
        <section class="slyder__slydes">
            <section class="slyder__slyde slyde">
                <img class="slyde__img" alt="Изображение слайда 1">
                <h4 class="slyde__header">Слайд 1</h4>
                <p class="slyde__desc">Описание</p>
            </section>
            <section class="slyder__slide slyde">
                <img class="slyde__img" alt="Изображение слайда 2">
                <h4 class="slyde__header">Слайд 2</h4>
                <p class="slyde__desc">Описание</p>
            </section>
            <section class="slyder__slyde slyde">
                <img class="slyde__img" alt="Изображение слайда 3">
                <h4 class="slyde__header">Слайд 3</h4>
                <p class="slyde__desc">Описание</p>
            </section>
            <section class="slyder__slyde slyde">
                <img class="slyde__img" alt="Изображение слайда 4">
                <h4 class="slyde__header">Слайд 4</h4>
                <p class="slyde__desc">Описание</p>
            </section>
            <section class="slyder__slyde slyde">
                <img class="slyde__img" alt="Изображение слайда 5">
                <h4 class="slyde__header">Слайд 5</h4>
                <p class="slyde__desc">Описание</p>
            </section>
        </section>
    </section>
    <section class="interests">
        <h2 class="interests__header">Вам может быть интересно</h2>
        <section class="interests__items">
            <section class="interests__item new-prods">
                <img class="new-prods__img" src="" alt="Новинки">
                <h3 class="new-prods__header">Новинки</h3>
            </section>
            <section class="interests__item disc-prods">
                <img class="disc-prods__img" src="" alt="Товары со скидками">
                <h3 class="disc-prods__header">Со скидками</h3>
            </section>
            <section class="interests__item brands">
                <img class="brands__img" src="" alt="Бренды">
                <h3 class="brands__header">Бренды</h3>
            </section>
        </section>
    </section>
    <section class="day-goods">
        <h2 class="day-goods__header">Товары дня</h2>
        <section class="day-goods__items">
            <section class="day-goods__item prod">
                <img class="prod__img" src="" alt="Товар дня 1">
                <h3 class="prod__header">Товар дня 1</h3>
                <ul class="prod__params params">
                    <li class="params__price">Цена</li>
                    <li class="params__views">Просмотры</li>
                    <li class="params__reviews">Отзывы</li>
                </ul>
            </section>
            <section class="day-goods__item prod">
                <img class="prod__img" src="" alt="Товар дня 2">
                <h3 class="prod__header">Товар дня 2</h3>
                <ul class="prod__params params">
                    <li class="params__price">Цена</li>
                    <li class="params__views">Просмотры</li>
                    <li class="params__reviews">Отзывы</li>
                </ul>
            </section>
            <section class="day-goods__item prod">
                <img class="prod__img" src="" alt="Товар дня 3">
                <h3 class="prod__header">Товар дня 3</h3>
                <ul class="prod__params params">
                    <li class="params__price">Цена</li>
                    <li class="params__views">Просмотры</li>
                    <li class="params__reviews">Отзывы</li>
                </ul>
            </section>
        </section>
    </section>
    <section class="popular-prods">
        <h2 class="popular-prods__header">Часто просматриваемые</h2>
        <section class="popular-prods__items">
            <section class="popular-prods__item prod">
                <img class="prod__img" src="" alt="Часто просматриваемый товар 1">
                <h3 class="prod__header">Часто просматриваемый товар 1</h3>
                <ul class="prod__params params">
                    <li class="params__price">Цена</li>
                    <li class="params__views">Просмотры</li>
                    <li class="params__reviews">Отзывы</li>
                </ul>
            </section>
            <section class="popular-prods__item prod">
                <img class="prod__img" src="" alt="Часто просматриваемый товар 2">
                <h3 class="prod__header">Часто просматриваемый товар 2</h3>
                <ul class="prod__params params">
                    <li class="params__price">Цена</li>
                    <li class="params__views">Просмотры</li>
                    <li class="params__reviews">Отзывы</li>
                </ul>
            </section>
            <section class="popular-prods__item prod">
                <img class="prod__img" src="" alt="Часто просматриваемый товар 3">
                <h3 class="prod__header">Часто просматриваемый товар 3</h3>
                <ul class="prod__params params">
                    <li class="params__price">Цена</li>
                    <li class="params__views">Просмотры</li>
                    <li class="params__reviews">Отзывы</li>
                </ul>
            </section>
        </section>
    </section>
{% endblock %}